apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "node-local-dns.fullname" . }}
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    {{- include "node-local-dns.labels" . | nindent 4 }}
data:
  Corefile: |
    {{ .Values.config.pillarDnsDomain }}:53 {
        errors
        cache {
                success 9984 30
                denial 9984 5
        }
        reload
        loop
        bind {{ .Values.config.pillarLocalDns }} {{ .Values.config.pillarDnsServer }}
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9253
        health {{ .Values.config.pillarLocalDns }}:8080
        }
    in-addr.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind {{ .Values.config.pillarLocalDns }} {{ .Values.config.pillarDnsServer }}
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9253
        }
    ip6.arpa:53 {
        errors
        cache 30
        reload
        loop
        bind {{ .Values.config.pillarLocalDns }} {{ .Values.config.pillarDnsServer }}
        forward . __PILLAR__CLUSTER__DNS__ {
                force_tcp
        }
        prometheus :9253
        }
    .:53 {
        errors
        cache 30
        reload
        loop
        bind {{ .Values.config.pillarLocalDns }} {{ .Values.config.pillarDnsServer }}
        forward . __PILLAR__UPSTREAM__SERVERS__
        prometheus :9253
        }
